@api = https://gestor-de-club.vercel.app/api


GET {{api}}/jugadores
###
GET {{api}}/cuotas
###
GET {{api}}/eventos
###
GET {{api}}/gastos
###
GET {{api}}/recaudacion





###
POST https://gestor-de-club.vercel.app/api/jugadores
Content-Type: application/json

{

  "nombre":"Mauri",
  "apellido":"Gimenez",
  "dni": "44444544",
  "celular": "2616095070",
  "celularEmergencia": "2616095070",
  "categoria":"VETERANO",
  "fechaNacimiento": "34343"
}


