@api = https://gestor-de-club.vercel.app/api
@apieventoLocal = http://localhost:3000/api/eventos



GET {{api}}/jugadores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJTYW1pciIsInBhc3N3b3JkIjoic2FtaXJiZWx0cmFuIiwicm9sZSI6IkNPQlJBRE9SIiwiaWF0IjoxNzI5NTQ3NTUzLCJleHAiOjE3Mjk1NTExNTN9.9lzOAiF_IFv5ubp4Blnm_x-AZaMUPxerRtSAib0peFg

###

GET {{apieventoLocal}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJDb21pc2lvbiIsInBhc3N3b3JkIjoiZGl4YSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyOTU0ODkxMCwiZXhwIjoxNzI5NTUyNTEwfQ.RK8t-c4418G7DwsRZ11or94TvHwIn1YrtDeGzOdSkN8



###
GET {{api}}/cuotas
###
GET {{api}}/eventos
###
GET {{api}}/gastos
###
GET {{api}}/recaudacion

###
POST {{api}}/login
Content-Type: application/json

{

  "nombre":"Daniel",
  "password":"danisnake"
}

###
POST {{api}}/login
Content-Type: application/json

{

  "nombre":"Samir",
  "password":"samirbeltran"
}
###
POST {{api}}/login
Content-Type: application/json

{

  "nombre":"Comision",
  "password":"dixa"
}



###
POST https://gestor-de-club.vercel.app/api/jugadores
Content-Type: application/json

{

  "nombre":"Mauri",
  "apellido":"Gimenez",
  "dni": "44444544",
  "celular": "2616095070",
  "celularEmergencia": "2616095070",
  "categoria":"VETERANO",
  "fechaNacimiento": "34343"
}


